---
title: "Example-Imageblurring"
author: "Zitian Wu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example-Imageblurring}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# High-dimensional Gaussian sampling using R

This is a package for high-dimensional Gaussian sampling. All the algorithms are described in this paper, https://doi.org/10.1137/20M1371026.

## To install the package
Run following codes in console to install the package 'GaussianSamplin'.
```{r, results='asis', eval=FALSE}
install.packages("devtools")
library(devtools)
install_github("Zitian-Wu/GaussianSampling")
```

This is an example of blurring image using the algorithm 'GEDA'. https://doi.org/10.1137/20M1371026

# Image Blurring


```{r}
circ <- function(x) {
  n<-length(x)
  matrix(x[matrix(1:n,n+1,n+1,byrow=T)[c(1,n:2),1:n]],n,n)
}

rotList <- function(L,n) {
  if (n==0) return(L)
  c(tail(L,n),head(L,-n))
}
rowFun <- function(n,matList) do.call(rbind,rotList(matList,n))
bcMat <- function(matList) {
  n <- length(matList)
  do.call(cbind,lapply(0:(n-1),rowFun,matList))
}
# bcMat(list(diag(3),matrix(1:9,nrow=3),matrix(4,nrow=3,ncol=3)))

# three functions of Matrix Vector multiplication
Qx <- function(q,x) {
  len <- length(q)
  Fq <- fft(q)
  xFi <- fft(x, inverse = T)
  output <- Re(fft(Fq * xFi)/len)
  return(output)
}

Qtx <- function(q,x) {
  len <- length(q)
  Fq <- fft(q)
  xFi <- fft(x, inverse = T)
  output <- Re(fft(Conj(Fq) * xFi)/len)
  return(output)
}

Qix <- function(q,x) {
  len <- length(q)
  Fq <- fft(q)
  xFi <- fft(x, inverse = T)
  output <- Re(fft(1/Fq * xFi)/len)
  return(output)
}
```

## image preview

Import png
```{r eval=TRUE}
library(png)
# testdata <- readPNG("C:/Users/37810/OneDrive/UF/2023spring/others/meeting/0307_convolution/Florida_Gators_gator_logo.svg.png")
# testdata <- readPNG("/Users/zitian/Library/CloudStorage/OneDrive-Personal/UF/2023spring/others/meeting/0307_convolution/Florida_Gators_gator_logo.svg.png")

data(image, package = "GaussianSampling")

data_nonoise <- testdata[,,1]
dim <- dim(testdata)[1]
len <- dim * dim

plot(c(1,10),c(1,10), type = "n")
rasterImage(testdata,1,1,10,10)

dim(testdata)
image(testdata[,,1], col = grey.colors(2))

testdata_grey <- rowMeans(testdata[,,-4], dims = 2)
dim(testdata_grey)
image(testdata_grey, col = grey.colors(2))

theta_ture <- as.vector(testdata_grey)

# build a smaller matrix
dim_s <- 50
len_s <- dim_s * dim_s

# testdata_ss <- testdata_grey[(501:550)-100,(501:550)-100]
# testdata_ss <- testdata_grey[(1:50)+90,(1:50)+205]
testdata_ss <- testdata[(1:50)+90,(1:50)+205,1]
image(testdata_ss)
# fields


# generate y, the noised data or observed data
theta_ture_ss <- cbind(as.vector(testdata_ss), rep(1:dim_s, dim_s), rep(1:dim_s, each=dim_s))

distance <- as.matrix((dist(theta_ture_ss[,2:3]))^2)
a <- 3
S <- exp(-distance/a)
S[which(S <= 1e-15)] <- 0
bw <- sum(S[1,]!=0)-1
s1 <- S[1,]
for (i in 1:bw) {
  s1[len_s-i+1] <- s1[1+i]
}
S <- circ(s1)
Fs1 <- fft(s1)
sigma <- 0.1 # need to sample
a1 <- 1; b1 <- 1
set.seed(10)
error <- rnorm(len_s, sd = sigma)
y_s <- S %*% theta_ture_ss[,1] + error
image(matrix(y_s,dim_s))



# Prior on Theta
delta <- c(4,-1,rep(0,len_s-3),-1)
delta[dim_s+1] <- delta[len_s - (dim_s+1) + 2] <- -1


Delta <- circ(delta)
Fq2 <- fft(delta)

alpha1 <- 22
alpha2 <- 110 # need to sample

Fq2[1] <- alpha1
Fq2[-1] <- Fq2[-1] * alpha2


# Calculate the mu
t1 <- Sys.time()
{
  q1 <- colSums(S*S[,1]) / sigma
  q2 <- colSums(Delta*Delta[,1])*alpha2 + alpha1/len_s
  q <- q1+q2
  
  Fq_inv <- 1/fft(q)
  Q_inv <- circ(Re(fft(Fq_inv)/len_s))
}
t2 <- Sys.time()
time1 <- t2 - t1

# t1 <- Sys.time()
# {
#   Q <- (t(S)/sigma) %*% S + crossprod(Delta) + 1/len_s
#   Q_i <- solve(Q)
# }
# t2 <- Sys.time()
# time2 <- t2 - t1
# 
# range(Q_inv-Q_i)
# time1; time2

mu <- y_s / sigma
mu <- Qtx(s1, mu)
mu <- Qix(q1+q2, mu)

# mu2 <- Q_inv %*% t(S) %*%y_s /sigma
# range(mu2-mu)
  
  

# Sampling
sigma <- 0.1 # it is sigma^2, element of the Matrix Gamma
omega <- 0.9 * min(sigma) / max(abs(Fs1))^2 # 0.2
# omega <- 1e-04
Totalitr <- 1000
burnin <- 500

# initialization
u1 <- rep(0,len_s)
thetaold <- rep(0,len_s)
theta <- matrix(0, Totalitr, len_s)

err <- rep(0,Totalitr)
sigmam <- rep(0,Totalitr)
# sigma0 <- sd(lm(y_s ~ S-1)$residuals)
# simga0 <- 0.1

# sigmahat <- sd((y_s~S)$residuals)#sigma_ini#sd(y)
# print(sigmahat)

library(glmnet)
las <- cv.glmnet(S, y_s)
las2 <- glmnet(S, y_s, lambda = las$lambda.min)
pred_las2 <- predict.glmnet(las2, S)
sigmahat <- sd(pred_las2 - y_s)

library(fields)
for (i in 1:Totalitr) {
  t1 <- Sys.time()
  
  # sample sigma^2
  err[i] <- sum((y_s-Qx(s1, thetaold))^2)
  # a1p <- a1+len_s/2
  # b1p <- b1+err[i]/2
  # 
  # sigma <- 1/rgamma(1, a1p, b1p)
  # sigmam[i] <- sigma

  
  a <- 1/rgamma(1, 1 + len_s/2, err[i]/2)
  gen <- sigma

  D_check <- dcauchy(sqrt(a),0, sigmahat, log=T)-dcauchy(sqrt(sigma),0, sigmahat, log=T)

  u <- runif(1)

  if(log(u) < D_check){
    gen <- a
  }
  sigma <- gen
  
  print(sigma)
  
  # sample sigma with half cauchy prior
  # a <- 1 / rgamma(1, 1/2, 1/sigmahat^2)
  # alpha <- 1/2
  # eta <- 1/a
  # sigma <- 1 / rgamma(1, alpha + len_s/2, eta + sum((y_s-Qx(s1, thetaold))^2)/2)

  # update mu
  mu <- y_s / sigma
  mu <- Qtx(s1, mu)
  q1 <- colSums(S*S[,1]) / sigma
  mu <- Qix(q1+q2, mu)

  
  # sample u2
  # mu_u2 = G_1 * u_1, using properties of fft on circulant matrix where G_1 is circulant
  mu_u2 <- Re(fft(Fs1 * fft(u1, inverse = T))) / len_s # S %*% u1
  # mu_u2 <- S %*% u1
  # mu_u2 <- Re(fft(fft(s1) * fft(u1), inverse = T)) / len_s. Only if matrix S is symmetric

  # Q_u2 = Lambda_1 = 1 / a

  u2 <- mu_u2 + rnorm(len_s) * sqrt(sigma)

  # print(c(range(u2), "u2"))
  # print(range(mu_u2 - S %*% u1))

  # Sample u1
  Q1x <- function(x) { # Q1 %*% x
    return(Re(fft(fft(Re(fft(fft(x) * Fs1, inverse = T)/len_s) / sigma) * Conj(Fs1), inverse = T)/len_s))
  }
  # mu_u1 = theta - omega (Q1*theta - G1T*Lambda_1^{-1}*u2)
  mu_u1 <- thetaold - omega * Q1x(thetaold) + omega * Re(fft(Conj(Fs1) * fft(u2 * sigma, inverse = T))/len_s)

  u1 <- mu_u1 + rnorm(len_s) * sqrt(omega)
  
  # print(c(range(u1), "u1"))

  # Sample theta
  Q2x <- function(x) { # Q2 %*% x
    return(Re(fft(fft(x) * (Fq2)^2 + c(alpha1,rep(0,len_s-1)), inverse = T)/len_s))
  }
  Fq_theta <- 1/omega + abs(Fq2)^2 # = fft(q2 + c(1,rep(0,len_s-1))/omega)
  # mu_theta =
  mu_theta <- Re(fft(fft(u1/omega - Q1x(u1) + Q1x(mu) + Q2x(mu)) / Fq_theta, inverse = T)/len_s)
  theta[i,] <- mu_theta + Re(fft(fft(rnorm(len_s)) / sqrt(Fq_theta), inverse = T)/len_s)
  # theta[i,] <- mu_theta + Qix(sqrt(Fq_theta), rnorm(len_s))

  thetaold <- theta[i,]
  
  if(i %% 100 == 0) {
    image.plot(matrix(theta[i,],dim_s), main = paste("sampled at", i))
  }
  
  t2 <- Sys.time()
}



sum((theta[Totalitr,]-theta_ture_ss[,1])^2)

theta_sample <- theta[-(1:burnin),]
muhat <- apply(theta_sample, 2, mean)
sum((muhat-theta_ture_ss[,1])^2) / len_s

image.plot(matrix(muhat,dim_s), main = "sampled, mean of theta hat after burning")
image.plot(testdata_ss, main = "true, theta")
image.plot(matrix(y_s,dim_s), main = "noised, y")


resu1 <- matrix(mu_theta,dim_s) # 22, 110
# 23, 100 for gator2


# 2. sample alpha 





```
